// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbipkqciYjquG1HkoaK5hEuJONKGi0Un0',
    appId: '1:1081235498424:web:e899f7509e61647c611b4d',
    messagingSenderId: '1081235498424',
    projectId: 'watsapdemo',
    authDomain: 'watsapdemo.firebaseapp.com',
    storageBucket: 'watsapdemo.appspot.com',
    measurementId: 'G-ZF49NQ9EGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMMH1ouAvbh-7CYl2mQZkuiy2cdUMU6NI',
    appId: '1:1081235498424:android:9989471483e92190611b4d',
    messagingSenderId: '1081235498424',
    projectId: 'watsapdemo',
    storageBucket: 'watsapdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWxx4ifDPD0RFsdI1OmstpWxFklLfa42U',
    appId: '1:1081235498424:ios:86bda5ee375d1798611b4d',
    messagingSenderId: '1081235498424',
    projectId: 'watsapdemo',
    storageBucket: 'watsapdemo.appspot.com',
    iosBundleId: 'com.example.watsapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWxx4ifDPD0RFsdI1OmstpWxFklLfa42U',
    appId: '1:1081235498424:ios:a0cfbd1b48b32a1d611b4d',
    messagingSenderId: '1081235498424',
    projectId: 'watsapdemo',
    storageBucket: 'watsapdemo.appspot.com',
    iosBundleId: 'com.example.watsapApp.RunnerTests',
  );
}
